"use client";

import { useState } from "react";
import { Download, Printer, FileText, FileIcon, Loader2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { toast } from "sonner";

interface ExportSection {
  title: string;
  content: string;
}

interface ExportMenuProps {
  title?: string;
  sections?: ExportSection[];
}

function buildHtml(title: string, sections: ExportSection[]): string {
  const sectionHtml = sections
    .map(
      (s) =>
        `<div style="margin-bottom:24px;">` +
        `<h2 style="font-size:14pt;font-weight:bold;margin-bottom:8px;color:#333;border-bottom:1px solid #ddd;padding-bottom:4px;">${escapeHtml(s.title)}</h2>` +
        `<div style="font-size:11pt;line-height:1.7;color:#444;white-space:pre-wrap;">${escapeHtml(s.content)}</div>` +
        `</div>`
    )
    .join("");

  return `
    <div style="font-family:Georgia,'Times New Roman',Times,serif;padding:40px;max-width:800px;margin:0 auto;">
      <div style="text-align:center;margin-bottom:32px;border-bottom:2px solid #333;padding-bottom:16px;">
        <h1 style="font-size:18pt;font-weight:bold;margin:0 0 4px 0;color:#111;">${escapeHtml(title)}</h1>
        <p style="font-size:10pt;color:#666;margin:0;">Generated by QanoonAI &mdash; ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}</p>
      </div>
      ${sectionHtml}
    </div>
  `;
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

async function exportPdf(title: string, sections: ExportSection[]) {
  const html2pdf = (await import("html2pdf.js")).default;
  const container = document.createElement("div");
  container.innerHTML = buildHtml(title, sections);
  document.body.appendChild(container);

  try {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    await (html2pdf() as any)
      .set({
        margin: [15, 15, 15, 15],
        filename: `${title.replace(/[^a-zA-Z0-9 ]/g, "").slice(0, 50)}.pdf`,
        html2canvas: { scale: 2, useCORS: true },
        jsPDF: { unit: "mm", format: "a4", orientation: "portrait" },
        pagebreak: { mode: ["avoid-all", "css", "legacy"] },
      })
      .from(container)
      .save();
  } finally {
    document.body.removeChild(container);
  }
}

function exportWord(title: string, sections: ExportSection[]) {
  const html = `
    <html xmlns:o='urn:schemas-microsoft-com:office:office'
          xmlns:w='urn:schemas-microsoft-com:office:word'
          xmlns='http://www.w3.org/TR/REC-html40'>
    <head><meta charset="utf-8"><title>${escapeHtml(title)}</title></head>
    <body>${buildHtml(title, sections)}</body>
    </html>
  `;

  const blob = new Blob(["\ufeff", html], { type: "application/msword" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${title.replace(/[^a-zA-Z0-9 ]/g, "").slice(0, 50)}.doc`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function ExportMenu({ title = "Document", sections }: ExportMenuProps) {
  const [exporting, setExporting] = useState(false);

  const handlePdf = async () => {
    if (!sections || sections.length === 0) {
      toast.error("No content to export");
      return;
    }
    setExporting(true);
    try {
      await exportPdf(title, sections);
      toast.success(`${title} exported as PDF`);
    } catch (err) {
      console.error("PDF export error:", err);
      toast.error("Failed to export PDF");
    } finally {
      setExporting(false);
    }
  };

  const handleWord = () => {
    if (!sections || sections.length === 0) {
      toast.error("No content to export");
      return;
    }
    try {
      exportWord(title, sections);
      toast.success(`${title} exported as Word`);
    } catch (err) {
      console.error("Word export error:", err);
      toast.error("Failed to export Word document");
    }
  };

  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button variant="outline" size="sm" disabled={exporting}>
          {exporting ? (
            <Loader2 className="h-4 w-4 mr-2 animate-spin" />
          ) : (
            <Download className="h-4 w-4 mr-2" />
          )}
          Export
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end">
        <DropdownMenuItem onClick={handlePdf} disabled={exporting}>
          <FileText className="h-4 w-4 mr-2" />
          Export as PDF
        </DropdownMenuItem>
        <DropdownMenuItem onClick={handleWord}>
          <FileIcon className="h-4 w-4 mr-2" />
          Export as Word
        </DropdownMenuItem>
        <DropdownMenuItem onClick={() => window.print()}>
          <Printer className="h-4 w-4 mr-2" />
          Print
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  );
}
